env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

    # For rclone with google drive or any cloud! After first commit pushing, login to https://cirrus-ci.com , click top left corner 3 dot menu, click repository(yourname/aosp-builder) > Repository Settings > Secured Variables > enter content of ~/.config/rclone/rclone.conf (from pc where you setup rclone) > ENCRYPT, copy that ENCRYPTED hash
    # ENCRYPTED variables is unique for every repository, so you cant use my one, create you rclone config https://rclone.org/drive/#making-your-own-client-id
    rclone_config: "ENCRYPTED[c4491bb34efcfd58c2ad846a4958a705d1b64bc905861416bfa2ad1126678a99e47b920c5b47af8fab1f2490e967fd8d]"
    bot_api_code: "ENCRYPTED[8565f596b029d4ab11e044f61a89388998733b005c6a6e90ff7591cabfdea685418de0a74edc3468123b5ede2566bd0e]"

task:
    name: xpub # Project name
    timeout_in: 120m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      dockerfile: Dockerfile  # It has built-in setup environment + repo, aria2, rclone, pigz, username ci, and email ci@ci.ci [You can use your own docker image if you want, or you can use this one too!]
      cpu: 8  #8 or less cpu for dummy build, 8 cpu for the final build, 8cpu highest for free accounts. Don't try to use more than 8cpu as free user, you may get blocked by ci.
      memory: 32G # So that we can have ram when needed, 32G highest
    #download_ccache_script: # To download ccache in background
     # - ./d_cache # Ccache download script
    sync_script: # To sync source
      - ./sync # Source sync script
    cook_build_script: # Actual build script foreground
      - ./cook # Build script to run
    upload_ccache_script: # Upload ccache to cloud foreground
      - ./u_cache # Ccache uploading script
